(rule ((targets (iso8859_2.ml))
       (deps (maps/8859-2.TXT))
       (action (run ${exe:../src/uuuui.exe} maps/8859-2.TXT iso8859_2.ml))))

(rule ((targets (iso8859_16.ml))
       (deps (maps/8859-16.TXT))
       (action (run ${exe:../src/uuuui.exe} maps/8859-16.TXT iso8859_16.ml))))

(rule ((targets (iso8859_9.ml))
       (deps (maps/8859-9.TXT))
       (action (run ${exe:../src/uuuui.exe} maps/8859-9.TXT iso8859_9.ml))))

(rule ((targets (iso8859_1.ml))
       (deps (maps/8859-1.TXT))
       (action (run ${exe:../src/uuuui.exe} maps/8859-1.TXT iso8859_1.ml))))

(rule ((targets (iso8859_11.ml))
       (deps (maps/8859-11.TXT))
       (action (run ${exe:../src/uuuui.exe} maps/8859-11.TXT iso8859_11.ml))))

(rule ((targets (iso8859_3.ml))
       (deps (maps/8859-3.TXT))
       (action (run ${exe:../src/uuuui.exe} maps/8859-3.TXT iso8859_3.ml))))

(rule ((targets (iso8859_10.ml))
       (deps (maps/8859-10.TXT))
       (action (run ${exe:../src/uuuui.exe} maps/8859-10.TXT iso8859_10.ml))))

(rule ((targets (iso8859_6.ml))
       (deps (maps/8859-6.TXT))
       (action (run ${exe:../src/uuuui.exe} maps/8859-6.TXT iso8859_6.ml))))

(rule ((targets (iso8859_7.ml))
       (deps (maps/8859-7.TXT))
       (action (run ${exe:../src/uuuui.exe} maps/8859-7.TXT iso8859_7.ml))))

(rule ((targets (iso8859_5.ml))
       (deps (maps/8859-5.TXT))
       (action (run ${exe:../src/uuuui.exe} maps/8859-5.TXT iso8859_5.ml))))

(rule ((targets (iso8859_13.ml))
       (deps (maps/8859-13.TXT))
       (action (run ${exe:../src/uuuui.exe} maps/8859-13.TXT iso8859_13.ml))))

(rule ((targets (iso8859_15.ml))
       (deps (maps/8859-15.TXT))
       (action (run ${exe:../src/uuuui.exe} maps/8859-15.TXT iso8859_15.ml))))

(rule ((targets (iso8859_14.ml))
       (deps (maps/8859-14.TXT))
       (action (run ${exe:../src/uuuui.exe} maps/8859-14.TXT iso8859_14.ml))))

(rule ((targets (iso8859_8.ml))
       (deps (maps/8859-8.TXT))
       (action (run ${exe:../src/uuuui.exe} maps/8859-8.TXT iso8859_8.ml))))

(rule ((targets (iso8859_4.ml))
       (deps (maps/8859-4.TXT))
       (action (run ${exe:../src/uuuui.exe} maps/8859-4.TXT iso8859_4.ml))))

